const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');

/**
 * Build an Excel buffer from attendance rows.
 * @param {Array} rows  attendance records
 * @param {string} date  YYYY-MM-DD
 */
async function buildExcel(rows, date) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'AttendTrack';
  wb.created = new Date();

  const ws = wb.addWorksheet(`Attendance ${date}`);

  // Title row
  ws.mergeCells('A1:G1');
  const title = ws.getCell('A1');
  title.value = `Attendance Report — ${date}`;
  title.font = { bold: true, size: 14 };
  title.alignment = { horizontal: 'center' };

  ws.addRow([]);

  // Header
  const header = ws.addRow(['#', 'Student ID', 'Name', 'Section', 'Status', 'Time In', 'Time Out', 'Duration']);
  header.eachCell(cell => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } };
    cell.alignment = { horizontal: 'center' };
  });

  // Column widths
  ws.columns = [
    { width: 5 }, { width: 14 }, { width: 26 }, { width: 14 },
    { width: 12 }, { width: 12 }, { width: 12 }, { width: 12 },
  ];

  // Data rows
  rows.forEach((r, i) => {
    const row = ws.addRow([
      i + 1,
      r.student_id,
      r.name,
      r.section || '',
      r.status,
      r.time_in || '—',
      r.time_out || '—',
      r.duration || '—',
    ]);
    const isPresent = r.status === 'PRESENT';
    row.getCell(5).font = { color: { argb: isPresent ? 'FF16A34A' : 'FF6B7280' }, bold: true };
    if (i % 2 === 1) {
      row.eachCell(cell => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
      });
    }
  });

  // Summary
  ws.addRow([]);
  const present = rows.filter(r => r.status === 'PRESENT').length;
  ws.addRow(['', '', '', '', `Present: ${present}`, `Absent: ${rows.length - present}`, `Rate: ${rows.length ? Math.round((present / rows.length) * 100) : 0}%`]);

  const buf = await wb.xlsx.writeBuffer();
  return buf;
}

/**
 * Build a PDF buffer from attendance rows.
 */
function buildPDF(rows, date) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text('AttendTrack', { align: 'center' });
    doc.fontSize(13).font('Helvetica').text(`Attendance Report — ${date}`, { align: 'center' });
    doc.moveDown();

    // Stats
    const present = rows.filter(r => r.status === 'PRESENT').length;
    const absent = rows.length - present;
    const rate = rows.length ? Math.round((present / rows.length) * 100) : 0;
    doc.fontSize(11).text(`Total: ${rows.length}   Present: ${present}   Absent: ${absent}   Rate: ${rate}%`, { align: 'center' });
    doc.moveDown();

    // Table header
    const tableTop = doc.y;
    const cols = { num: 50, id: 80, name: 200, status: 310, timeIn: 380, timeOut: 450 };

    doc.fontSize(10).font('Helvetica-Bold');
    doc.rect(50, tableTop - 5, 510, 18).fill('#4F46E5');
    doc.fillColor('white');
    doc.text('#', cols.num, tableTop, { width: 25 });
    doc.text('Student ID', cols.id, tableTop, { width: 110 });
    doc.text('Name', cols.name, tableTop, { width: 100 });
    doc.text('Status', cols.status, tableTop, { width: 65 });
    doc.text('Time In', cols.timeIn, tableTop, { width: 65 });
    doc.text('Time Out', cols.timeOut, tableTop, { width: 65 });
    doc.fillColor('black').font('Helvetica').fontSize(9);

    let y = tableTop + 20;
    rows.forEach((r, i) => {
      if (y > 750) { doc.addPage(); y = 50; }
      if (i % 2 === 0) doc.rect(50, y - 3, 510, 16).fill('#F9FAFB');
      doc.fillColor(r.status === 'PRESENT' ? '#16A34A' : '#6B7280');
      doc.text(String(i + 1), cols.num, y, { width: 25 });
      doc.fillColor('#111827');
      doc.text(r.student_id, cols.id, y, { width: 110 });
      doc.text(r.name, cols.name, y, { width: 100 });
      doc.fillColor(r.status === 'PRESENT' ? '#16A34A' : '#6B7280').font('Helvetica-Bold');
      doc.text(r.status, cols.status, y, { width: 65 });
      doc.fillColor('#111827').font('Helvetica');
      doc.text(r.time_in || '—', cols.timeIn, y, { width: 65 });
      doc.text(r.time_out || '—', cols.timeOut, y, { width: 65 });
      y += 18;
    });

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#9CA3AF').text(`Generated by AttendTrack on ${new Date().toLocaleString()}`, { align: 'center' });
    doc.end();
  });
}

module.exports = { buildExcel, buildPDF };
